export interface Exercise {
  slug: string;
  namePt: string;
  muscleGroups: string[];
  equipmentRequired: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  descriptionPt: string;
  contraindications: string[];
}

export const EXERCISES: Exercise[] = [
  // ===== Bodyweight Exercises (Home + Gym) - 10 exercises =====
  {
    slug: 'flexao',
    namePt: 'Flexão de Braço',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipmentRequired: ['bodyweight'],
    difficulty: 'beginner',
    descriptionPt: 'Deite-se de bruços, mãos na largura dos ombros, empurre o corpo para cima mantendo o core ativado.',
    contraindications: ['shoulder_pain', 'wrist_pain'],
  },
  {
    slug: 'agachamento',
    namePt: 'Agachamento Livre',
    muscleGroups: ['legs', 'glutes', 'core'],
    equipmentRequired: ['bodyweight'],
    difficulty: 'beginner',
    descriptionPt: 'Pés na largura dos ombros, desça como se fosse sentar, joelhos alinhados com os pés.',
    contraindications: ['knee_pain'],
  },
  {
    slug: 'burpee',
    namePt: 'Burpee',
    muscleGroups: ['full_body', 'cardio'],
    equipmentRequired: ['bodyweight'],
    difficulty: 'intermediate',
    descriptionPt: 'Agachamento, apoie as mãos, salto para prancha, flexão, pule de volta e salte para cima.',
    contraindications: ['knee_pain', 'back_pain', 'shoulder_pain'],
  },
  {
    slug: 'prancha',
    namePt: 'Prancha Abdominal',
    muscleGroups: ['core', 'abs'],
    equipmentRequired: ['bodyweight'],
    difficulty: 'beginner',
    descriptionPt: 'Apoie os antebraços e pontas dos pés, mantenha o corpo reto, core contraído.',
    contraindications: ['back_pain', 'shoulder_pain'],
  },
  {
    slug: 'mountain-climber',
    namePt: 'Mountain Climber',
    muscleGroups: ['core', 'abs', 'cardio'],
    equipmentRequired: ['bodyweight'],
    difficulty: 'intermediate',
    descriptionPt: 'Posição de prancha alta, alterne trazendo os joelhos em direção ao peito rapidamente.',
    contraindications: ['wrist_pain', 'shoulder_pain'],
  },
  {
    slug: 'afundo',
    namePt: 'Afundo',
    muscleGroups: ['legs', 'glutes'],
    equipmentRequired: ['bodyweight'],
    difficulty: 'beginner',
    descriptionPt: 'Dê um passo à frente, desça até o joelho traseiro quase tocar o chão, suba e alterne.',
    contraindications: ['knee_pain'],
  },
  {
    slug: 'triceps-banco',
    namePt: 'Tríceps no Banco',
    muscleGroups: ['triceps', 'shoulders'],
    equipmentRequired: ['bodyweight', 'bench'],
    difficulty: 'beginner',
    descriptionPt: 'Apoie as mãos em um banco atrás de você, pernas estendidas, desça flexionando os cotovelos.',
    contraindications: ['shoulder_pain', 'elbow_pain'],
  },
  {
    slug: 'abdominal',
    namePt: 'Abdominal Tradicional',
    muscleGroups: ['abs', 'core'],
    equipmentRequired: ['bodyweight'],
    difficulty: 'beginner',
    descriptionPt: 'Deitado, joelhos flexionados, mãos atrás da cabeça, levante o tronco contraindo o abdômen.',
    contraindications: ['neck_pain', 'back_pain'],
  },
  {
    slug: 'polichinelo',
    namePt: 'Polichinelo',
    muscleGroups: ['full_body', 'cardio'],
    equipmentRequired: ['bodyweight'],
    difficulty: 'beginner',
    descriptionPt: 'Salte abrindo pernas e braços simultaneamente, depois volte à posição inicial.',
    contraindications: ['knee_pain'],
  },
  {
    slug: 'ponte-gluteo',
    namePt: 'Ponte de Glúteo',
    muscleGroups: ['glutes', 'legs', 'core'],
    equipmentRequired: ['bodyweight'],
    difficulty: 'beginner',
    descriptionPt: 'Deitado de costas, joelhos flexionados, levante o quadril contraindo os glúteos.',
    contraindications: ['back_pain'],
  },

  // ===== Dumbbell Exercises (Home + Gym) - 10 exercises =====
  {
    slug: 'supino-halteres',
    namePt: 'Supino com Halteres',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipmentRequired: ['dumbbells', 'bench'],
    difficulty: 'intermediate',
    descriptionPt: 'Deitado em banco, halteres ao lado do peito, empurre para cima até estender os braços.',
    contraindications: ['shoulder_pain'],
  },
  {
    slug: 'desenvolvimento-halteres',
    namePt: 'Desenvolvimento com Halteres',
    muscleGroups: ['shoulders', 'triceps'],
    equipmentRequired: ['dumbbells'],
    difficulty: 'intermediate',
    descriptionPt: 'Sentado ou em pé, halteres ao lado da cabeça, empurre para cima até estender os braços.',
    contraindications: ['shoulder_pain'],
  },
  {
    slug: 'rosca-direta',
    namePt: 'Rosca Direta com Halteres',
    muscleGroups: ['biceps'],
    equipmentRequired: ['dumbbells'],
    difficulty: 'beginner',
    descriptionPt: 'Em pé, cotovelos fixos ao lado do corpo, flexione os braços levantando os halteres.',
    contraindications: ['elbow_pain'],
  },
  {
    slug: 'remada-unilateral',
    namePt: 'Remada Unilateral',
    muscleGroups: ['back', 'biceps'],
    equipmentRequired: ['dumbbells', 'bench'],
    difficulty: 'intermediate',
    descriptionPt: 'Apoie um joelho no banco, puxe o halter em direção ao quadril, cotovelo próximo ao corpo.',
    contraindications: ['back_pain'],
  },
  {
    slug: 'elevacao-lateral',
    namePt: 'Elevação Lateral',
    muscleGroups: ['shoulders'],
    equipmentRequired: ['dumbbells'],
    difficulty: 'beginner',
    descriptionPt: 'Em pé, braços ao lado do corpo, levante os halteres lateralmente até a altura dos ombros.',
    contraindications: ['shoulder_pain'],
  },
  {
    slug: 'triceps-testa',
    namePt: 'Tríceps Testa',
    muscleGroups: ['triceps'],
    equipmentRequired: ['dumbbells', 'bench'],
    difficulty: 'intermediate',
    descriptionPt: 'Deitado, braços estendidos para cima, flexione apenas os cotovelos levando halteres à testa.',
    contraindications: ['elbow_pain'],
  },
  {
    slug: 'agachamento-goblet',
    namePt: 'Agachamento Goblet',
    muscleGroups: ['legs', 'glutes', 'core'],
    equipmentRequired: ['dumbbells'],
    difficulty: 'beginner',
    descriptionPt: 'Segure um halter na altura do peito, agache mantendo o tronco ereto.',
    contraindications: ['knee_pain'],
  },
  {
    slug: 'afundo-halteres',
    namePt: 'Afundo com Halteres',
    muscleGroups: ['legs', 'glutes'],
    equipmentRequired: ['dumbbells'],
    difficulty: 'intermediate',
    descriptionPt: 'Halteres nas mãos, execute o afundo tradicional com carga adicional.',
    contraindications: ['knee_pain'],
  },
  {
    slug: 'crucifixo',
    namePt: 'Crucifixo com Halteres',
    muscleGroups: ['chest'],
    equipmentRequired: ['dumbbells', 'bench'],
    difficulty: 'intermediate',
    descriptionPt: 'Deitado em banco, braços abertos com leve flexão nos cotovelos, junte os halteres acima do peito.',
    contraindications: ['shoulder_pain'],
  },
  {
    slug: 'remada-curvada',
    namePt: 'Remada Curvada com Halteres',
    muscleGroups: ['back', 'biceps'],
    equipmentRequired: ['dumbbells'],
    difficulty: 'intermediate',
    descriptionPt: 'Inclinado para frente, puxe os halteres em direção ao abdômen, cotovelos próximos ao corpo.',
    contraindications: ['back_pain'],
  },

  // ===== Gym Equipment Exercises - 10 exercises =====
  {
    slug: 'supino-barra',
    namePt: 'Supino Reto com Barra',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipmentRequired: ['barbell', 'bench'],
    difficulty: 'intermediate',
    descriptionPt: 'Deitado em banco, desça a barra até o peito e empurre para cima.',
    contraindications: ['shoulder_pain'],
  },
  {
    slug: 'agachamento-barra',
    namePt: 'Agachamento com Barra',
    muscleGroups: ['legs', 'glutes', 'core'],
    equipmentRequired: ['barbell', 'squat_rack'],
    difficulty: 'advanced',
    descriptionPt: 'Barra nas costas, pés na largura dos ombros, agache mantendo a coluna neutra.',
    contraindications: ['knee_pain', 'back_pain'],
  },
  {
    slug: 'levantamento-terra',
    namePt: 'Levantamento Terra',
    muscleGroups: ['back', 'legs', 'glutes', 'core'],
    equipmentRequired: ['barbell'],
    difficulty: 'advanced',
    descriptionPt: 'Pegada na barra, levante mantendo a coluna reta, quadril e joelhos estendidos.',
    contraindications: ['back_pain'],
  },
  {
    slug: 'puxada-frontal',
    namePt: 'Puxada Frontal',
    muscleGroups: ['back', 'biceps'],
    equipmentRequired: ['cable_machine'],
    difficulty: 'beginner',
    descriptionPt: 'Segure a barra acima da cabeça, puxe até a altura do peito contraindo as costas.',
    contraindications: ['shoulder_pain'],
  },
  {
    slug: 'remada-sentado',
    namePt: 'Remada Sentada',
    muscleGroups: ['back', 'biceps'],
    equipmentRequired: ['cable_machine'],
    difficulty: 'beginner',
    descriptionPt: 'Sentado, puxe o cabo em direção ao abdômen, ombros para trás.',
    contraindications: ['back_pain'],
  },
  {
    slug: 'leg-press',
    namePt: 'Leg Press',
    muscleGroups: ['legs', 'glutes'],
    equipmentRequired: ['leg_press_machine'],
    difficulty: 'beginner',
    descriptionPt: 'Sentado na máquina, empurre a plataforma com os pés, joelhos alinhados.',
    contraindications: ['knee_pain'],
  },
  {
    slug: 'rosca-polia',
    namePt: 'Rosca Bíceps na Polia',
    muscleGroups: ['biceps'],
    equipmentRequired: ['cable_machine'],
    difficulty: 'beginner',
    descriptionPt: 'De frente para a polia baixa, puxe a barra flexionando os cotovelos.',
    contraindications: ['elbow_pain'],
  },
  {
    slug: 'triceps-polia',
    namePt: 'Tríceps na Polia',
    muscleGroups: ['triceps'],
    equipmentRequired: ['cable_machine'],
    difficulty: 'beginner',
    descriptionPt: 'De frente para a polia alta, empurre a barra para baixo estendendo os cotovelos.',
    contraindications: ['elbow_pain'],
  },
  {
    slug: 'desenvolvimento-maquina',
    namePt: 'Desenvolvimento na Máquina',
    muscleGroups: ['shoulders', 'triceps'],
    equipmentRequired: ['shoulder_press_machine'],
    difficulty: 'beginner',
    descriptionPt: 'Sentado na máquina, empurre as alças para cima até estender os braços.',
    contraindications: ['shoulder_pain'],
  },
  {
    slug: 'cadeira-extensora',
    namePt: 'Cadeira Extensora',
    muscleGroups: ['legs'],
    equipmentRequired: ['leg_extension_machine'],
    difficulty: 'beginner',
    descriptionPt: 'Sentado na máquina, estenda as pernas levantando o peso com os quadríceps.',
    contraindications: ['knee_pain'],
  },
];
